language: scala
scala:
   - 2.11.2
jdk:
  - oraclejdk8
env:
  global:
  - ENCRYPTION_LABEL: "af05534c7e9c"
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers
before_install:
  - git clone https://github.com/scalatra/scalatra-website.git
  - git clone https://github.com/scalatra/scalatra.git
  - wget https://github.com/spf13/hugo/releases/download/v0.19/hugo_0.19-64bit.deb
  - sudo dpkg -i hugo_0.19-64bit.deb
before_script:
  - sudo chmod +x /usr/local/bin/sbt
script: ./hello.sh
