name: Deploy website

on:
  push:
    branches: [ master ]

jobs:
  deploy_website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout scalatra-website
        uses: actions/checkout@v2
        with:
          repository: scalatra/scalatra-website
          path: scalatra-website
      - name: Checkout scalatra
        uses: actions/checkout@v2
        with:
          repository: scalatra/scalatra
          path: scalatra
          fetch-depth: 0
      - name: Checkout scatra-docbuild
        uses: actions/checkout@v2
        with:
          repository: scalatra/scalatra-docbuild
          path: scalatra-docbuild
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8    
      - name: Install Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.19/hugo_0.19-64bit.deb
          sudo dpkg -i hugo_0.19-64bit.deb
      - name: script
        env:
          ENCRYPTION_LABEL: af05534c7e9c
        run: ./hello.sh
